name: shoesly
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #di
  get_it: ^7.7.0
  injectable: ^2.4.1
  #generator
  json_annotation: ^4.8.1
  auto_route: ^8.1.3
  freezed_annotation: ^2.4.1
  #state-management
  freezed: ^2.5.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  #firebase-services
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  #loading
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  faker_dart: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator:                   
  build_runner:   
  injectable_generator:
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/