// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYy4i8de8MV58RBffGLzM9y4KjKDui1I',
    appId: '1:97392203803:web:b30b801d03b74edfd080be',
    messagingSenderId: '97392203803',
    projectId: 'kbuddy-a6986',
    authDomain: 'kbuddy-a6986.firebaseapp.com',
    storageBucket: 'kbuddy-a6986.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9X23aIWl4nP6IEt7EkJXA147_OXX2lM',
    appId: '1:97392203803:android:85db3f413d0fed9bd080be',
    messagingSenderId: '97392203803',
    projectId: 'kbuddy-a6986',
    storageBucket: 'kbuddy-a6986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYeL1Pfa93WnHahBC_JVXUv-FDT2aB00Y',
    appId: '1:97392203803:ios:aa754958fa71841fd080be',
    messagingSenderId: '97392203803',
    projectId: 'kbuddy-a6986',
    storageBucket: 'kbuddy-a6986.appspot.com',
    androidClientId: '97392203803-3r6ka79mmug1j2fub0vaehpb994r8e0g.apps.googleusercontent.com',
    iosClientId: '97392203803-5jv09hc0gmioo16h2tgmvm0bki7fgjbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYeL1Pfa93WnHahBC_JVXUv-FDT2aB00Y',
    appId: '1:97392203803:ios:aa754958fa71841fd080be',
    messagingSenderId: '97392203803',
    projectId: 'kbuddy-a6986',
    storageBucket: 'kbuddy-a6986.appspot.com',
    androidClientId: '97392203803-3r6ka79mmug1j2fub0vaehpb994r8e0g.apps.googleusercontent.com',
    iosClientId: '97392203803-5jv09hc0gmioo16h2tgmvm0bki7fgjbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOjzTA9hFgVOQI-OLVlZZLyHQ-MTSP4-8',
    appId: '1:97392203803:web:6e167c07eb00cf75d080be',
    messagingSenderId: '97392203803',
    projectId: 'kbuddy-a6986',
    authDomain: 'kbuddy-a6986.firebaseapp.com',
    storageBucket: 'kbuddy-a6986.appspot.com',
  );
}
